## Numpy: 'the backbone of machine learning'

- Library = collection of packages
- Package = collection of modules
- Module = collection of files (.py, scripts, etc)

In [1]:
import numpy as np

the main backbone of Numpy is an array which is a list inside of paranthesis: np.array([1,2,3,4,5])

In [48]:
my_array = np.array([1,2,3,4,5])

In [4]:
my_array

array([1, 2, 3, 4, 5])

* referenced similarily to a list by using indexing

In [5]:
my_array[2]

3

Multidimensional lists is where Numpy comes to save the day

In [6]:
list_of_lists = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

* does NOT keep the shape, returns in line format seperated by commas

In [7]:
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
list_of_lists[0]

[1, 2, 3]

In [11]:
list_of_lists[0][1]

2

In [14]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

In [15]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
matrix[0,1]

2

^^ going down the first row and grabbing the second column

* Matrix = Row X Column
* Matrix KEEPS the shape of the input
* using np.nan turns integers into floats?

** can use slicing **
* matrix[1:] grabs all of the columns

In [17]:
matrix[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [20]:
matrix[:1]

array([[1, 2, 3]])

In [19]:
matrix[1:2]

array([[4, 5, 6]])

### I do not understand slicing and splicing with arrays

Boolean Mask = [False, True, False, True]

"A customer that pays a certain amount per month that you want to look at" is an example

In [34]:
mask = [False, True, False, True, False]

In [35]:
my_array[mask]

array([2, 4])

In [36]:
matrix_mask = [False, True, False,],[False, True, False]

In [37]:
matrix[matrix_mask]

array([5])

* returns the mask without the shape

In [41]:
my_list = [1,2,3,4,5]
list_plus_one = []

for i in my_list:
    list_plus_one.append(i+1)
list_plus_one

[2, 3, 4, 5, 6]

In [42]:
[i+1 for i in my_list]

[2, 3, 4, 5, 6]

In [43]:
my_array + 1

array([2, 3, 4, 5, 6])

In [44]:
my_array - 5 

array([-4, -3, -2, -1,  0])

In [46]:
my_array * 10

array([10, 20, 30, 40, 50])

In [47]:
my_array / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [49]:
my_array

array([1, 2, 3, 4, 5])

When using boolean masking with arrays
1. filter
2. manipulate

#### comparisons with operators IS the beginning to predictive modeling and filtering the data

In [50]:
my_array > 2

array([False, False,  True,  True,  True])

What if I want my numbers? Or the 'name' of the mask?

In [51]:
my_array[my_array > 2]

array([3, 4, 5])

Using AND/OR statements works too!
* have to use byte-wise operators

In [52]:
my_array[(my_array > 2) & (my_array < 4)]

array([3])

* byte-wise with numbers
* logical operators with phrasing and other values


* even = my_array[(my_array % 2 == 0)
* odd = my_array[(my_array % 2 == 1)

In [57]:
my_array[(my_array % 2 == 1) & (my_array > 2)]

array([3, 5])

In [59]:
np.random.randn(10)

array([-0.89760128, -0.6404043 , -0.80266829,  1.15034918,  0.5198909 ,
        1.06317091,  0.37338185, -0.55334109, -1.39373046,  0.03499589])

Normal = Bell = Dossi(?) Distribution Curve

USE SEABORN FOR VISUAL DISPLAYS OF INFORMATION

In [66]:
np.random.randn(3,3) # (x,x) means x by x, row x column for a random distribution

array([[-2.06960223,  0.05754884, -0.8833404 ],
       [-1.45490448,  0.21710383, -1.42459846],
       [ 0.04107258, -0.589331  , -0.83619401]])

In [62]:
np.zeros((3,3)) # fills a matrix full of zeros!

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
np.ones((3,3)) # fills a matrix full of ones!

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [65]:
np.full((3,3), 10) # fills a matrix of size by size, value

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [67]:
np.arange(10) # not inclusive, gives array in the range specified

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.arange(1, 10) # NO ZERO

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.arange(1, 10, 2) # start at one, end at 10, step every 2 

array([1, 3, 5, 7, 9])

In [75]:
np.arange(1,5,0.5) # works with decimals too

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

We use this to generate simulated data to SEE the relationship between X and Y before adding in data

In [79]:
np.linspace(1,4,5) # not inclusive # splitting up the data into even 'bins' # we can specify what bin we want
                    # helpful when doing plotting by creating these bins to pass in an 
                    # x-valule and plot in a y-value

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [80]:
my_array

array([1, 2, 3, 4, 5])

### descriptive statistics

In [82]:
my_array.mean() # grabs descriptive statistics

3.0

Something inherent to classes - you can string functions at the end of the object IF the object is from the same library

* we don't need to specify the library we are pulling these functions from because we applied the function TO the list
    * we didn't put the object into the function

In [85]:
my_array.mean(), my_array.sum(), my_array.max(), my_array.min(), my_array.std()

(3.0, 15, 5, 1, 1.4142135623730951)

In [87]:
my_array.mean().sum().max().min() # huh?

3.0